### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by AmeenAli** [dvlab-research/LISA#10]
Hello

I have downloaded the datasets as specified in the README

I have run the following command for training : 

`deepspeed --master_port=24999 train_ds.py \
  --version="PATH_TO_LLaVA" \
  --dataset_dir='./dataset' \
  --vision_pretrained="PATH_TO_SAM" \
  --exp_name="lisa-7b" \
  --weight='PATH_TO_pytorch_model.bin' \
  --eval_only`

However, I receive the following error : 

`Traceback (most recent call last):
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameenali/LISA/utils/dataset.py", line 244, in __getitem__
    return *data[0], inference
  File "/home/ameenali/LISA/utils/sem_seg_dataset.py", line 284, in __getitem__
    classes = [self.data2classes[ds][class_id - 1] for class_id in unique_label]
  File "/home/ameenali/LISA/utils/sem_seg_dataset.py", line 284, in <listcomp>
    classes = [self.data2classes[ds][class_id - 1] for class_id in unique_label]
IndexError: index 182 is out of bounds for axis 0 with size 182
`

Any idea why this is happening ?

**Comment by X-Lai** [comment]
Hi, it seems that the class index is out of range. It runs well in my side. May I know if you are using the most recent code or modified the code?

Can you print out `ds` and `len(self.data2classes[ds])` to figure out what's going on inside?

**Comment by AmeenAli** [comment]
I am using 3 A5000 cards, and i get 3 different outputs : 
182 , 24 , 150 (I assume each output is for each GPU card)

**Comment by X-Lai** [comment]
`len(self.data2classes[ds])` is correct. Since I observe this line `classes = [self.data2classes[ds][class_id - 1] for class_id in unique_label]` actually does not exist in current code. Did you modify the code? If this is the case, please pull your local repo to the latest version.

Another possibility is that the datasets may not be correct. Please check the annotations of `cocostuff` and make sure the labels cannot be equal or larger than 182.

**Comment by AmeenAli** [comment]
Hi
Thank you for your fast respone!

I have cloned the code again and re-ran (BTW I am downloaind the annotations_trainval2017.zip from https://github.com/nightrome/cocostuff#downloads for the cocostuff annotations, is that right?)

I get the same error with the code in your repo : 

`Traceback (most recent call last):
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameenali/anaconda3/envs/ameen/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ameenali/LISA/utils/dataset.py", line 244, in __getitem__
    return *data[0], inference
  File "/home/ameenali/LISA/utils/sem_seg_dataset.py", line 285, in __getitem__
    classes = [self.data2classes[ds][class_id] for class_id in unique_label]
  File "/home/ameenali/LISA/utils/sem_seg_dataset.py", line 285, in <listcomp>
    classes = [self.data2classes[ds][class_id] for class_id in unique_label]
IndexError: index 182 is out of bounds for axis 0 with size 182`

**Comment by X-Lai** [comment]
Sorry for the ambiguity. Please download annotation from this link: http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip. I will fix it right now.

**Comment by AmeenAli** [comment]
@X-Lai this contains the train2017 and val2017 but not the annotations, can you provide the annotations files as well ?

**Comment by X-Lai** [comment]
Hi, the `.png` files in train2017 and val2017 are already the annotations. And you need to copy the `.jpg` COCO2017 image files into the `train2017`. Sorry that I add the `annotations` directory in the directory tree structure, just ignore it. I will fix it right away.

**Comment by AmeenAli** [comment]
what do you mean by "And you need to copy the .jpg COCO2017 image files into the train2017" ?

**Comment by X-Lai** [comment]
Hi, I just update the processing script, please pull the most latest repo, and you do not need to copy .jpg files now.
