### ISSUE TITLE
'llava' is already used by a Transformers config, pick another name.

### ISSUE THREAD

**Issue by uppppppp** [dvlab-research/LISA#109]
Has anyone encountered this issue?"
ValueError: 'llava' is already used by a Transformers config, pick another name.
Traceback (most recent call last):
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/train_ds.py", line 16, in <module>
    from model.LISA import LISAForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/LISA.py", line 14, in <module>
    from .llava.model.language_model.llava_llama import (LlavaLlamaForCausalLM,
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaConfig, LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/language_model/llava_llama.py", line 166, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 828, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
Traceback (most recent call last):
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/train_ds.py", line 16, in <module>
    from model.LISA import LISAForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/LISA.py", line 14, in <module>
    from .llava.model.language_model.llava_llama import (LlavaLlamaForCausalLM,
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaConfig, LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/language_model/llava_llama.py", line 166, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 828, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
Traceback (most recent call last):
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/train_ds.py", line 16, in <module>
    from model.LISA import LISAForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/LISA.py", line 14, in <module>
    from .llava.model.language_model.llava_llama import (LlavaLlamaForCausalLM,
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaConfig, LlavaLlamaForCausalLM
  File "/mnt/beegfs/groups/cv/mamingming/workspace/LISA/model/llava/model/language_model/llava_llama.py", line 166, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/mnt/beegfs/groups/cv/tengfei.mao/envs/lisa/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 828, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.

**Comment by CoderZhangYx** [comment]
use an older transformers version, for example 4.31.0

**Comment by saunair** [comment]
How about commenting out the auto-register? Is it crucial?
