### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Ringhu** [dvlab-research/LISA#117]
Hi, thank you for your excellent work. I trained my own lisa model, after training and merged the weights. But when i try to run the chat.py for inference, the error occured after input the prompt and image path:
```
Traceback (most recent call last):
  File "/cluster/home/hulining/proj/LISA/chat.py", line 263, in <module>
    main(sys.argv[1:])
  File "/cluster/home/hulining/proj/LISA/chat.py", line 221, in main
    output_ids, pred_masks = model.evaluate(
  File "/cluster/home/hulining/proj/LISA/model/LISA.py", line 354, in evaluate
    outputs = self.generate(
  File "/cluster/home/hulining/anaconda3/envs/lisa/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/cluster/home/hulining/anaconda3/envs/lisa/lib/python3.10/site-packages/transformers/generation/utils.py", line 1606, in generate
    return self.greedy_search(
  File "/cluster/home/hulining/anaconda3/envs/lisa/lib/python3.10/site-packages/transformers/generation/utils.py", line 2454, in greedy_search
    outputs = self(
  File "/cluster/home/hulining/anaconda3/envs/lisa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/hulining/proj/LISA/model/LISA.py", line 166, in forward
    return super().forward(**kwargs)
  File "/cluster/home/hulining/proj/LISA/model/llava/model/language_model/llava_llama.py", line 88, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/cluster/home/hulining/proj/LISA/model/llava/model/llava_arch.py", line 110, in prepare_inputs_labels_for_multimodal
    (attention_mask.shape[0], past_key_values[-1][-1].shape[-2] + 1),
AttributeError: 'NoneType' object has no attribute 'shape'
```
i traced the error and found the solution, which is change the `past_key_values` to `None` in code [llava_llama.py](https://github.com/dvlab-research/LISA/blob/main/model/llava/model/language_model/llava_llama.py), but i don't know why it happen, can you help me? Thank you.

**Comment by Yonggie** [comment]
Same, any helpers?

**Comment by SoluteToNight** [comment]
Try python 3.9 with transformers==4.31.0, it works on my computer. @Ringhu

**Comment by Amark-cheey** [comment]
> Try python 3.9 with transformers==4.31.0, it works on my computer. @Ringhu

Even after applying these modifications, my code is still throwing the same error.

**Comment by ShawnHuang497** [comment]
I met the same issue. did anyone fix it? @Yonggie @Amark-cheey @Ringhu @SoluteToNight @dreamingaa

**Comment by andyhandsom6** [comment]
I met the same error. Has anyone solved it? Any help is highly appreciated! @Yonggie @Amark-cheey @Ringhu @SoluteToNight @ShawnHuang497

**Comment by ymkasad** [comment]
您好·，请问您解决·了·这个问题了吗

**Comment by TousenKaname** [comment]
I met the same error.

**Comment by xiaomengyc** [comment]
> Try python 3.9 with transformers==4.31.0, it works on my computer. [@Ringhu](https://github.com/Ringhu)

Python 3.10.15 with transformers==4.31.0 also works!
