### ISSUE TITLE
LISA model_forward bug, only occurs when inference.

### ISSUE THREAD

**Issue by Roberyan** [dvlab-research/LISA#132]
I replace the backbone of llava to another projects' llava, they both build on the original llava model.

When I run train_ds.py file, the training mode works well but the inference raises bug:
```
Traceback (most recent call last):
  File "/home/user/LISA-RS/train_ds.py", line 605, in <module>
    main(sys.argv[1:])
  File "/home/user/LISA-RS/train_ds.py", line 394, in main
    giou, ciou = validate(val_loader, model_engine, epoch, writer, args)
  File "/home/user/LISA-RS/train_ds.py", line 566, in validate
    output_dict = model_engine(**input_dict)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1855, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/LISA/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/user/LISA-RS/model/LISA.py", line 177, in forward
    return self.model_forward(**kwargs)
  File "/home/user/LISA-RS/model/LISA.py", line 277, in model_forward
    pred_embeddings = last_hidden_state[seg_token_mask]
IndexError: The shape of the mask [1, 338] at index 0 does not match the shape of the indexed tensor [33, 338, 256] at index 0
[2024-06-06 10:00:21,670] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1165665
[2024-06-06 10:00:21,670] [ERROR] [launch.py:325:sigkill_handler] ['/home/user/anaconda3/envs/LISA/bin/python', '-u', 'train_ds.py', '--local_rank=0', '--version=BigData-KSU/RS-llava-v1.5-7b-LoRA', '--dataset_dir=../remote_LISA_dataset', '--vision_pretrained=./download_weights/sam_vit_h_4b8939.pth', '--dataset=reason_seg', '--sample_rates=1', '--exp_name=model_test', '--batch_size=1', '--grad_accumulation_steps=1', '--steps_per_epoch=1'] exits with return code = 1
```
at first the bug is from `output_hidden_states_level = torch.cat(output_hidden_states, dim=0)`, which turns out to be a type error, I fix this by `output_hidden_states_level = torch.cat(output_hidden_states[0], dim=0)`

however, the following error comes as `IndexError: The shape of the mask [1, 338] at index 0 does not match the shape of the indexed tensor [33, 338, 256] at index 0`, I print the things and find that this should be a problem in these code:
```
hidden_states = []

assert len(self.model.text_hidden_fcs) == 1
hidden_states.append(self.model.text_hidden_fcs[0](output_hidden_states[-1]))

last_hidden_state = torch.stack(hidden_states, dim=-1).sum(dim=-1)
print(f"inference last_hidden_state shape: {last_hidden_state.shape}\n\n\n")
pred_embeddings = last_hidden_state[seg_token_mask]
```
specifically, `seg_token_mask.shape (final): torch.Size([1, 338])`
`inference last_hidden_state shape: torch.Size([33, 338, 256]) ` I have no idea why this happens.

I update my transformers from 4.31 to 4.35 and peft from 0.4 to 0.5, but this does not seem like a version problem to me. The original setting works well. All I change is the backbone and package version.

**Comment by Roberyan** [comment]
I update my transformers from 4.31 to 4.35 and peft from 0.4 to 0.5, but this does not seem like a version problem to me

**Comment by Yonggie** [comment]
Same. looking for helper

**Comment by Roberyan** [comment]
@Yonggie I solved mine, my problem is solved for the LISA's llava backbone only return the last hidden state, while the training return the whole hidden state. I solved this by something like returning `hidden_state[-1]` in the inference mode. Hope this helps.
