### ISSUE TITLE
DeepSpeed Load Problem

### ISSUE THREAD

**Issue by Noietch** [dvlab-research/LISA#5]
when i trying to load a model using deepspeed
```bash
CUDA_VISIBLE_DEVICES=0 python3 chat.py --version='xinlai/LISA-13B-llama2-v0' --precision='fp16' --load_in_4bit
```

It results in :
```bash
[2023-08-07 14:45:14,038] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:19<00:00,  6.41s/it]
[2023-08-07 14:45:46,446] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.10.0, git-hash=unknown, git-branch=unknown
[2023-08-07 14:45:46,449] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[2023-08-07 14:45:46,450] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Using /home/dml/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/dml/.cache/torch_extensions/py39_cu117/transformer_inference/build.ninja...
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer_inference...
Time to load transformer_inference op: 0.5588159561157227 seconds
[2023-08-07 14:45:47,705] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 1, 'intermediate_size': 35389440, 'heads': 40, 'num_hidden_layers': -1, 'dtype': torch.float16, 'pre_layer_norm': True, 'norm_type': <NormType.RMSNorm: 3>, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 1, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 0, 'rotate_half': True, 'rotate_every_two': False, 'return_tuple': True, 'mlp_after_attn': True, 'mlp_act_func_type': <ActivationFuncType.GATED_SILU: 4>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False, 'max_out_tokens': 1024, 'min_out_tokens': 1, 'scale_attn_by_inverse_layer_idx': False, 'enable_qkv_quantization': False, 'use_mup': False, 'return_single_tuple': False, 'set_empty_params': False, 'transposed_mode': False, 'use_triton': False, 'triton_autotune': False}
Using /home/dml/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module transformer_inference, skipping build step...
Loading extension module transformer_inference...
Time to load transformer_inference op: 0.08758425712585449 seconds
Traceback (most recent call last):
  File "/home/dml/yhq/LISA/chat.py", line 169, in <module>
    main(sys.argv[1:])
  File "/home/dml/yhq/LISA/chat.py", line 86, in main
    model_engine = deepspeed.init_inference(model=model, 
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 192, in __init__
    self._apply_injection_policy(config)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/inference/engine.py", line 426, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 523, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 766, in replace_module
    replaced_module, _ = _replace_module(model, policy, state_dict=sd)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 847, in _replace_module
    _, layer_id = _replace_module(child,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 823, in _replace_module
    replaced_module = policies[child.__class__][0](child,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 500, in replace_fn
    new_module = replace_with_policy(child,
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 354, in replace_with_policy
    _container.apply_tensor_parallelism(mp_replace)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/containers/features/hybrid_engine.py", line 94, in apply_tensor_parallelism
    self.mlp_output_mp(mp_replace, reversed_dim=reversed_dim)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/containers/base.py", line 257, in mlp_output_mp
    self.module.mlp.output_w = mp_replace.copy(self.module.mlp.output_w, self._4hh_w, int8=reversed_dim)
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 109, in copy
    self.merge_assert(src_shape[inner_dim], dst_shape[self.in_dim])
  File "/home/dml/anaconda3/envs/lisa/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 43, in merge_assert
    assert dim1 > dim2, \
AssertionError: Merging tensors is not allowed here! Please use deepspeed load_checkpoint            for merging your checkpoints before replacing the transformer layer with            inference-kernels
```

**Comment by X-Lai** [comment]
Can you run this successfully?
```
CUDA_VISIBLE_DEVICES=0 python3 chat.py --version='xinlai/LISA-13B-llama2-v0' --precision='bf16' 
```

**Comment by Noietch** [comment]
The single graphics card I'm using doesn't have that much VRAM. Could you please let me know how much VRAM your inference uses?

**Comment by Noietch** [comment]
There seems to be an issue with your requirement file. peft requires a torch version greater than 1.13, and there is some duplication with Pillow. I suspect it might be a dependency version problem.

**Comment by X-Lai** [comment]
Can you try to change a version `deepspeed == 0.9.2`?

**Comment by X-Lai** [comment]
Thanks for reporting this issue, I will fix it soon.

**Comment by Noietch** [comment]
I have successfully run it using Torch 1.13, CUDA 11.7, and DeepSpeed 0.9.0. 
This line of code has an issue that could result in the weight file being loaded locally instead of from Hugging Face.https://github.com/dvlab-research/LISA/blob/c82295a4edf021a9cde58d69983d4edd6d9e320c/chat.py#L76C27-L76C27

**Comment by X-Lai** [comment]
Hi, Thanks for reporting this issue. We currently provide a workaround to hack the .cache directory, it works now when the model weights are directly from hf. Please check it out.

**Comment by wangzhaosongAha** [comment]
> 您的需求文件似乎存在问题。peft 需要高于 1.13 的 Torch 版本，并且与 Pillow 有一些重复。我怀疑这可能是依赖项版本问题。

Hello, I also encountered this problem, how did you solve it?
