### ISSUE TITLE
Run into problem with train.py and dataset.py

### ISSUE THREAD

**Issue by BrunoFANG1** [dvlab-research/LISA#66]
I have already downloaded all datasets and tried to train LISA with them, but I get the following issue when I run this: 

deepspeed --master_port=24999 train_ds.py \
--version="liuhaotian/llava-v1.5-7b" \
--dataset_dir='./dataset' \
--vision_pretrained="/mnt/gs21/scratch/anhaowei/LISA/pretrained_checkpoint/sam_vit_h_4b8939.pth" \
--dataset="sem_seg||refer_seg||vqa||reason_seg" \
--sample_rates="9,3,3,1" \
--exp_name="lisa-7b" \
--image_size=256
##############################
Traceback (most recent call last):
  File "/mnt/home/anhaowei/anaconda3/envs/LISA/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/home/anhaowei/anaconda3/envs/LISA/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/mnt/gs21/scratch/anhaowei/LISA/utils/dataset.py", line 137, in collate_fn
    assert cur_len == total_len
AssertionError
##############################
Is that a problem related to dataset?

**Comment by AmrinKareem** [comment]
I have the same issue. Have you solved it @BrunoFANG1 ? Thanks!

**Comment by BrunoFANG1** [comment]
I did not solve it, I directly comment this line and it runs.

**Comment by JosephPai** [comment]
Same issue here.
@BrunoFANG1 If you comment this line, does it affect the performance?

**Comment by kravrolens** [comment]
Encountered the same problem, how to solve it?

**Comment by fredshentu** [comment]
same issue here.
