### ISSUE TITLE
KeyError: 'LlavaConfig'

### ISSUE THREAD

**Issue by BinZhu-ece** [dvlab-research/LISA#88]
Traceback (most recent call last):
  File "/remote-home/zhubin/LISA/chat.py", line 263, in <module>
    main(sys.argv[1:])
  File "/remote-home/zhubin/LISA/chat.py", line 76, in main
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
                                               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'LlavaConfig'

**Comment by BinZhu-ece** [comment]
> the same problem...have you solved it?

try to download this weights again and it runs successfully

**Comment by goodstudent9** [comment]
> > the same problem...have you solved it?
> 
> try to download this weights again and it runs successfully

yes，it is
